version: '3.7'

services:

  client:
    image: labprog/client
    # container_name: labprog-client
    command: ./start.sh
    restart: always
    ports:
      - "4200:4200"
    # stdin_open y tty mantienen el servidor funcionando sin commandos en ejecuci贸n
    stdin_open: true
    tty: true
    volumes:
      - ./src/client/:/home/node/
      # base
      - ./base/client/install.sh:/home/node/install.sh:ro
      - ./base/client/start.sh:/home/node/start.sh:ro
    depends_on:
      - server
  
  # 10.000km

  server:
    image: labprog/server
    # container_name: labprog-server
    command: ant start-docker
    restart: always
    ports:
      - "28002:8080"
      - "4848:4848"
      - "28001:1527"
    # stdin_open y tty mantienen el servidor funcionando sin commandos en ejecuci贸n
    stdin_open: true
    tty: true
    volumes:
      # Directorios de la aplicaci贸n
      - ./base/server/build.xml:/root/app/build.xml
      - ./base/server/config:/root/app/config
      - ./base/server/lib:/root/app/lib
      - ./base/server/etc/web.xml:/root/app/etc/web/WEB-INF/web.xml:ro
      #- ./base/server/etc/sql:/root/app/etc/sql
      # C贸digo
      - ./src/server/model:/root/app/src/model
      - ./src/server/servlet:/root/app/src/servlet
      - ./src/server/stateless:/root/app/src/stateless
      - ./src/server/etc/sql:/root/app/etc/sql
      # Etc
      - ./src/server/etc/persistence.xml:/root/app/etc/persistence/META-INF/persistence.xml:ro
      # Persistencia de glassfish y base de datos
      - glassfish:/usr/local/glassfish5/glassfish
      # Directorios de ejemplos
      # - ./ejemplos/server:/root/app/ejemplos

volumes:
  glassfish:
  
